[profile.default]
src = "contracts"
out = "artifacts"
libs = ["dependencies"]
remappings = [
    "@openzeppelin-contracts/=dependencies/openzeppelin-contracts/"
]

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
engine = "chc"

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${API_KEY_ALCHEMY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }


